name: Lint

on: workflow_call

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Get Cached Checkout
        with:
          name: checkout-${{ github.run_id }}
      - uses: actions/setup-go@v5
        name: Install Golang
        with:
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@v6
        name: Run golangci-lint
        with:
          args: --config=.golangci.yml
          version: latest
